Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/urls.py
from django.contrib import admin
from django.urls import path
from capacityWeb import views

app_name = '[capacityWeb]'
urlpatterns = [
    # 主页
    path('index/', views.index, name='index'),
    # 各景区详细信息
    path('meifeng/', views.meifeng, name='meifeng'),
    path('huangshanjian/', views.huangshanjian, name='huangshanjian'),
    path('tianchi/', views.tianchi, name='tianchi'),
    path('yueguang/', views.yueguang, name='yueguang'),
    path('longshan/', views.longshan, name='longsha'),
    path('yule/', views.yule, name='yule'),
    path('guihua/', views.guihua, name='guihua'),
    path('mishan/', views.mishan, name='mishan'),
    path('updatetodayTouristNums/', views.updatetodayTouristNums),
    path('getScenicHeartMapData/', views.getScenicHeartMapData),

]

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/mainproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from capacityWeb import views as capViews

urlpatterns = [
    path('admin/', admin.site.urls),
    # capacityWEB's TEMPLATE URL
    url(r'^index/', capViews.index),
    url(r'^latestwarn/', capViews.latestwarn),
    url(r'^test/', capViews.test),
    url(r'^addData/', capViews.addData),
    # VIEWS URL
    url(r'^getHeatMapNums/', capViews.getHeatMapNums),
    url(r'^getHeatMapScenic/', capViews.getHeatMapScenic),
    url(r'^getHeatMapCamera/', capViews.getHeatMapCamera),
    # 设置二级路由，请保留
    path('capacityWeb/', include('capacityWeb.urls', namespace='capacityWeb')),

]

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/models.py
from django.db import models


# Create your models here.

class Camera(models.Model):
    camid = models.CharField(db_column='camId', primary_key=True, max_length=11)  # Field name made lowercase.
    scenicid = models.ForeignKey('Scenic', models.DO_NOTHING, db_column='scenicId')  # Field name made lowercase.
    camplace = models.CharField(db_column='camPlace', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.
    camlng = models.FloatField(db_column='camLng', blank=True, null=True)  # Field name made lowercase.
    camlat = models.FloatField(db_column='camLat', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'camera'
        unique_together = (('camid', 'scenicid'),)


class Recordnums(models.Model):
    scenicid = models.ForeignKey('Scenic', models.DO_NOTHING, db_column='scenicId')  # Field name made lowercase.
    camid = models.ForeignKey(Camera, models.DO_NOTHING, db_column='camId', blank=True,
                              null=True)  # Field name made lowercase.
    nums = models.IntegerField(blank=True, null=True)
    year = models.IntegerField()
    month = models.IntegerField(blank=True, null=True)
    day = models.IntegerField(blank=True, null=True)
    hour = models.IntegerField(blank=True, null=True)
    minute = models.IntegerField(blank=True, null=True)
    sec = models.IntegerField(blank=True, null=True)
    createat = models.CharField(db_column='createAt', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.

    class Meta:

        db_table = 'recordnums'


class Recordwarnings(models.Model):
    warningid = models.AutoField(db_column='warningId', primary_key=True)  # Field name made lowercase.
    scenicid = models.CharField(db_column='scenicId', max_length=11, blank=True,
                                null=True)  # Field name made lowercase.
    camid = models.CharField(db_column='camId', max_length=11, blank=True, null=True)  # Field name made lowercase.
    level = models.IntegerField(blank=True, null=True)
    type = models.IntegerField(blank=True, null=True)
    createat = models.CharField(db_column='createAt', max_length=255, blank=True,
                                null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'recordwarnings'


class Scenic(models.Model):
    scenicid = models.CharField(db_column='scenicId', primary_key=True, max_length=11)  # Field name made lowercase.
    scenicname = models.CharField(db_column='scenicName', max_length=255, blank=True,
                                  null=True)  # Field name made lowercase.
    warning1nums = models.IntegerField(db_column='warning1Nums', blank=True, null=True)  # Field name made lowercase.
    warning2nums = models.IntegerField(db_column='warning2Nums', blank=True, null=True)  # Field name made lowercase.
    warning3nums = models.IntegerField(db_column='warning3Nums', blank=True, null=True)  # Field name made lowercase.
    lng = models.FloatField(blank=True, null=True)
    lat = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'scenic'

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/views.py
import time, datetime, json, random, itertools
import decimal
import numpy as np
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.db import connection
from django.utils.safestring import SafeString
from .models import Scenic, Recordnums, Recordwarnings, Camera
from dateutil.relativedelta import relativedelta
from django.db.models import Max, Sum


def test(request):
    result = Recordnums.objects.filter(minute__modEqual=5).values('scenicid', 'month')
    return render(request, 'test.html')


def addData(request):
    # 添加Recordwarnings表
    for i in range(20):
        curtime = datetime.datetime.now() + relativedelta(days=i) - relativedelta(years=1)
        for j in range(1, 9):
            level = random.randint(1, 3)
            Recordwarnings.objects.create(scenicid=j, camid=0, level=level, type=1, createat=str(curtime)[:19])
    # 添加Recordnums表
    for i in range(20):
        curtime = datetime.datetime.now() + relativedelta(days=i) - relativedelta(years=1)
        year = curtime.year
        month = curtime.month
        day = curtime.day
        hour = curtime.hour
        minute = curtime.minute
        sec = curtime.second
        for j in range(1, 9):
            for k in range(1, 16):
                nums = random.randint(1, 1000)
                sce_obj = Scenic(scenicid=j)
                cam_obj = Camera(scenicid=sce_obj, camid=k)
                Recordnums.objects.create(scenicid=sce_obj, camid=cam_obj, nums=nums, year=year, month=month, day=day,
                                          hour=hour,
                                          minute=minute, sec=sec, createat=str(curtime)[:19])
    return render(request, 'addData.html')


def getTime(request):
    t = datetime.datetime.now()
    data = {'current_time': str(t)[:17]}
    return HttpResponse(json.dumps(data))


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


class DecimalEncoder(json.JSONEncoder):
    def default(self, o):
        if isinstance(o, decimal.Decimal):
            return float(o)
        super(DecimalEncoder, self).default(o)


def get_current_week():
    monday, sunday = datetime.datetime.now(), datetime.datetime.now()
    one_day = datetime.timedelta(days=1)
    while monday.weekday() != 0:
        monday -= one_day
    while sunday.weekday() != 6:
        sunday += one_day
    # 返回当前的星期一前一天和星期天后一天
    return monday - relativedelta(days=1), sunday + relativedelta(days=1)


def get_time_dic():
    curtime = datetime.datetime.now()
    monday, sunday = datetime.datetime.now(), datetime.datetime.now()
    one_day = datetime.timedelta(days=1)
    while monday.weekday() != 0:
        monday -= one_day
    while sunday.weekday() != 6:
        sunday += one_day
    time_dic = {'monday': monday - relativedelta(days=1), 'sunday': sunday + relativedelta(days=1),
                'last_monday': monday - relativedelta(days=8), 'last_sunday': monday}
    lastmonth_time = curtime - relativedelta(months=1)
    time_dic['lastmonth_year'] = lastmonth_time.year
    time_dic['lastmonth_month'] = lastmonth_time.month
    time_dic['lastmonth'] = lastmonth_time
    # 返回timedate字典
    return time_dic


def getIntervalTouristNums(start, end, scenicid):
    """
    :param start:
    :param end:
    :return: 获得start-end时间端内某岛的人数
    """
    nums_this_Interval = Recordnums.objects.filter(scenicid=scenicid, year__range=[start.year, end.year],
                                                   month__range=[start.month, end.month],
                                                   day__range=[start.day, end.day],
                                                   ).values("nums")
    sum_ = 0
    for r in nums_this_Interval:
        sum_ += r['nums']
    return sum_


def getIntervalWarnNums(start, end, scenicid):
    """

    :param start:
    :param end:
    :param scenicid:
    :return: 获得某岛的一段时间内的预警次数
    """
    start_str = str(start)[:10]
    end = end + relativedelta(days=1)  # 因为是半闭合区间
    end_str = str(end)[:10]

    sum_ = 0
    result = Recordwarnings.objects.filter(scenicid=scenicid, createat__gt=start_str, createat__lt=end_str)
    for r in result:
        sum_ += 1

    return sum_


def getYouNeedInterval():
    """

    :return:获得本周起始时间，上一周起始时间，去年的本周起始时间，
            本月份起始时间，上一个月起始时间，去年本月起始时间
    """
    current_time = datetime.datetime.now()
    month_today = current_time
    month_start = current_time - relativedelta(days=current_time.day - 1)

    month_start_lastyear, month_today_lastyear = month_start - relativedelta(years=1), month_today - relativedelta(
        years=1)
    month_start_lastmonth, month_today_lastmonth = month_start - relativedelta(months=1), month_today - relativedelta(
        months=1)
    # 获得本月的起始时间，去年的本月起始时间，上个月的起始时间

    monday, sunday = get_current_week()
    sunday = current_time
    monday_lastyear, sunday_lastyear = monday - relativedelta(years=1), sunday - relativedelta(years=1)
    monday_lastweek, sunday_lastweek = monday - relativedelta(days=7), sunday - relativedelta(days=7)

    # 获得本周的起始时间，去年的本周起始时间，上周起始时间

    return monday, sunday, monday_lastweek, sunday_lastweek, monday_lastyear, sunday_lastyear, \
           month_start, month_today, month_start_lastmonth, month_today_lastmonth, month_start_lastyear, \
           month_today_lastyear


def getYearOverYearRate(nowDate, prevDate):
    """

    :param nowDate:
    :param prevDate:
    :return:返回同比增长率
    """
    return (nowDate - prevDate) / (nowDate + 1) * 100


def getMonthOverMonthRate(nowDate, prevDate):
    """

    :param nowDate:
    :param prevDate:
    :return: 返回环比增长率
    """
    return (nowDate - prevDate) / (prevDate + 1) * 100


def getScenicTouristNums(scenicid):
    """

    :param scenicid:
    :return: 得到某岛旅客人数
    """
    contexts = {}

    monday, sunday, monday_lastweek, sunday_lastweek, monday_lastyear, sunday_lastyear, \
    month_start, month_today, month_start_lastmonth, month_today_lastmonth, month_start_lastyear, \
    month_today_lastyear = getYouNeedInterval()

    # 获得本周的起始时间，去年的本周起始时间，上周起始时间
    # 本月份起始时间，上一个月起始时间，去年本月起始时间
    num_this_month = getIntervalTouristNums(month_start, month_today, scenicid)
    num_this_month_lastyear = getIntervalTouristNums(month_start_lastyear, month_today_lastyear, scenicid)
    num_this_month_lastmonth = getIntervalTouristNums(month_start_lastmonth, month_today_lastmonth, scenicid)
    # 通过getIntervalTouristNums获得本月份，去年本月份，上个月的游客人数

    month_yearOveryear_rate = getYearOverYearRate(num_this_month, num_this_month_lastyear)
    month_monthOvermonth_rate = getMonthOverMonthRate(num_this_month, num_this_month_lastmonth)
    contexts['month_yearOveryear_rate'] = month_yearOveryear_rate
    contexts['month_monthOvermonth_rate'] = month_monthOvermonth_rate
    contexts['num_this_month'] = num_this_month
    # 计算出月同比和环比增长率和环比率比保存到contexts中

    num_this_week = getIntervalTouristNums(monday, sunday, scenicid)
    num_this_week_lastyear = getIntervalTouristNums(monday_lastyear, sunday_lastyear, scenicid)
    num_this_week_lastweek = getIntervalTouristNums(monday_lastweek, sunday_lastweek, scenicid)
    # 通过getIntervalTouristNums获得本周，去年本周，上周的游客人数

    week_yearOveryear_rate = getYearOverYearRate(num_this_week, num_this_week_lastyear)
    week_weekOverweek_rate = getMonthOverMonthRate(num_this_week, num_this_week_lastweek)
    contexts['week_yearOveryear_rate'] = week_yearOveryear_rate
    contexts['week_weekOverweek_rate'] = week_weekOverweek_rate
    contexts['num_this_week'] = num_this_week
    # 计算出周的同比增长率和环比增长率并保存到contexts字典中

    return contexts


def getTouristNums():
    """
    游客人数模块，得到历史游客人数
    :return: context
    """
    context = {}
    # 当前时间
    current_time = datetime.datetime.now()
    # 所需时间
    time_dic = get_time_dic()
    # query_time_monday, query_time_sunday = str(time_dic['monday'])[:10], str(time_dic['sunday'])[:10]
    # query_time_monday_lastweek, query_time_sunday_lastweek = str(time_dic['last_monday'])[:10], str(time_dic['last_sunday'])[:10]
    query_time_monday, query_time_sunday = '2019-09-22', '2019-09-30'
    query_time_monday_lastweek, query_time_sunday_lastweek = '2019-09-15', '2019-09-23'
    # 去年同日期
    # monday_lastyear, sunday_lastyear = time_dic['monday'] - relativedelta(years=1), time_dic['sunday'] - relativedelta(years=1)
    # query_time_monday_lastyear, query_time_sunday_lastyear = str(monday_lastyear)[:10], str(sunday_lastyear)[:10]
    query_time_monday_lastyear, query_time_sunday_lastyear = '2018-09-22', '2018-09-30'
    with connection.cursor() as cursor:
        # 查询本周游客人数
        query = "SELECT SUM(nums) as rn_sum_week FROM recordnums WHERE createAt > %s AND createAt < %s"
        cursor.execute(query, [query_time_monday, query_time_sunday])
        rn_sum_week = dictfetchall(cursor)[0]['rn_sum_week']
        # 查询上一周游客人数
        query = "SELECT SUM(nums) as rn_sum_week_lastweek FROM recordnums WHERE createAt > %s AND createAt < %s"
        cursor.execute(query, [query_time_monday_lastweek, query_time_sunday_lastweek])
        rn_sum_week_lastweek = dictfetchall(cursor)[0]['rn_sum_week_lastweek']
        # 查询上一年本周游客人数
        query = "SELECT SUM(nums) as rn_sum_week_lastyear FROM recordnums WHERE createAt > %s AND createAt < %s"
        cursor.execute(query, [query_time_monday_lastyear, query_time_sunday_lastyear])
        rn_sum_week_lastyear = dictfetchall(cursor)[0]['rn_sum_week_lastyear']
        # 查询本月游客人数
        query = "SELECT SUM(nums) as rn_sum_month FROM recordnums WHERE `year`=%s AND `month` = %s"
        # cursor.execute(query, [current_time.year, current_time.month])
        cursor.execute(query, [2019, 9])
        rn_sum_month = dictfetchall(cursor)[0]['rn_sum_month']
        # 查询上一月游客人数

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/addData.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加数据</title>
</head>
<body>
<p>添加数据...</p>
</body>
</html>

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/gh_scenic.html
{% extends 'father.html' %}

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/hs_scenic.html
{% extends 'father.html' %}

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/latestwarn.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>最新预警信息</title>

    <!-- StyleSheet -->
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/latestwarn.css' %}">
    <link rel="shortcut icon" href="{% static 'img/icon.ico' %}" type="image/x-icon">
    <!-- JavaScript-->
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#mynavbar">
                <span class="sr-only">切换导航</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="{% static 'img/logo.jpg' %}">千岛湖承载量预警平台</a>
        </div>
        <div class="collapse navbar-collapse navbar-right" id="mynavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url '[capacityWeb]:index' %}"><i class="fa fa-home"></i>主页</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="false"><i
                            class="fa fa-star"></i>景区详情<span
                            class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'capacityWeb:meifeng' %}"><i class="fa fa-star"></i>梅峰岛</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'capacityWeb:huangshanjian' %}"><i class="fa fa-star"></i>黄山尖</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url '[capacityWeb]:tianchi' %}"><i class="fa fa-star"></i>天池岛</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url '[capacityWeb]:yueguang' %}"><i class="fa fa-star"></i>月光岛</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url '[capacityWeb]:longsha' %}"><i class="fa fa-star"></i>龙山岛</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url '[capacityWeb]:yule' %}"><i class="fa fa-star"></i>渔乐岛</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url '[capacityWeb]:guihua' %}"><i class="fa fa-star"></i>挂花岛</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url '[capacityWeb]:mishan' %}"><i class="fa fa-star"></i>蜜山岛</a></li>
                    </ul>
                </li>
                <li><a href="#"><i class="fa fa-exclamation-triangle"></i>最新预警</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-camera"></i>监控<b
                            class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#"><i class="fa fa-camera"></i>监控1</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-camera"></i>监控2</a></li>
                        <li class="divider"></li>
                        <li><a href="#"><i class="fa fa-camera"></i>监控3</a></li>
                    </ul>
                </li>
                <li><a href="#"><i class="fa fa-history"></i>历史预警</a></li>
                <li><a href="#"><i class="fa fa-folder"></i>后台管理</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid container-main">

</div>
<script>
    $('li').click(function () {
        $("li.active").removeClass("active");
        $(this).addClass("active");
    })
</script>
</body>
</html>

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/longshan_scenic.html
{% extends 'father.html' %}

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/mf_scenic.html
{% extends 'father.html' %}

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/ms_scenic.html
{% extends 'father.html' %}

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/tc_scenic.html
{% extends 'father.html' %}

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/yg_scenic.html
{% extends 'father.html' %}

Qiandao-Lake-Capacity-Warning-Web-Project/mainproject/capacityWeb/templates/yl_scenic.html
{% extends 'father.html' %}